name: E2E Test Suite

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  backend-integration-tests:
    runs-on: ubuntu-latest
    name: Backend Integration Tests
    
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_USER: test
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Run backend integration tests
        run: ./gradlew test --tests "*IntegrationTest"
        env:
          SPRING_PROFILES_ACTIVE: test
          
      - name: Upload backend test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-results
          path: build/test-results/test/
          
      - name: Upload backend test coverage
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage-report
          path: build/reports/jacoco/test/html/

  frontend-e2e-tests:
    runs-on: ubuntu-latest
    name: Frontend E2E Tests
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Java 21 (for backend)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
            e2e-tests/package-lock.json
          
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Install frontend dependencies
        run: cd frontend && npm ci
        
      - name: Install E2E test dependencies
        run: cd e2e-tests && npm ci
        
      - name: Install Playwright browsers
        run: cd e2e-tests && npx playwright install chromium firefox webkit
        
      - name: Build frontend for production
        run: cd frontend && npm run build
        
      - name: Start backend server
        run: ./gradlew bootRun &
        env:
          SPRING_PROFILES_ACTIVE: test
          
      - name: Wait for backend to start
        run: |
          timeout 120 bash -c 'until curl -f http://localhost:8080/actuator/health; do sleep 2; done'
          echo "Backend is ready"
          
      - name: Start frontend server
        run: cd frontend && npm start &
        env:
          CI: false
          
      - name: Wait for frontend to start
        run: |
          timeout 120 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
          echo "Frontend is ready"
          
      - name: Run Playwright E2E tests
        run: cd e2e-tests && npm run test
        env:
          CI: true
          
      - name: Upload E2E test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-test-results
          path: e2e-tests/test-results/
          
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          
      - name: Upload E2E test videos
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: e2e-test-videos
          path: e2e-tests/test-results/